NamuKiwi/urls.py
from django.contrib import admin
from django.urls import path, include
from NamuKiwi import views
from django.conf.urls import url

app_name = 'kiwi'

urlpatterns = [
    path('', views.MainPage, name='MainPage'),
    path('create/', views.CreatePage, name='CreatePage'),
    path('<str:page_subject>/', views.DetailPage, name='DetailPage'),
    path('<str:page_subject>/edit/', views.EditPage, name='EditPage'),
    path('<str:page_subject>/delete/', views.DeletePage, name='DeletePage'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('NamuKiwi.urls')),
]

NamuKiwi/models.py
from django.db import models

class PageData(models.Model):
    subject = models.CharField(max_length=200, primary_key=True)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return self.subject

# Create your models here.

NamuKiwi/forms.py
from django import forms
from .models import PageData

class EditForm(forms.ModelForm):
    class Meta:
        model = PageData  # 사용할 모델
        fields = ['content']
        widgets = {'content' : forms.Textarea(attrs={'row' : 10 , 'class' : 'editor', 'spellcheck' : 'false'})}
        
class CreateForm(forms.ModelForm):
    class Meta:
        model = PageData
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-subject', 'placeholder' : '새 문서 제목', 'spellcheck' : 'false'}),
            'content': forms.Textarea(attrs={'class': 'form-content', 'rows': 10, 'placeholder' : '새 문서 내용', 'spellcheck' : 'false'}),
        }

NamuKiwi/views.py
from django.shortcuts import get_object_or_404, redirect, render

from NamuKiwi.forms import EditForm, CreateForm
from .models import PageData
from django.utils import timezone


def MainPage(request):
    data_list = PageData.objects.order_by('create_date')
    if request.method == "POST":
        searchData = request.POST.get('search', '')
    else:
        searchData = ''
    context = {'pageDataList' : data_list, 'searchData' : searchData}
    return render(request, 'NamuKiwi/MainPage.html', context);

def DetailPage(request, page_subject):
    """
    pybo 목록 출력
    """
    data = PageData.objects.get(pk=page_subject)
    data_list = PageData.objects.order_by('create_date')
    context = {'pageData': data, 'pageDataList' : data_list}
    return render(request, 'NamuKiwi/DetailPage.html', context)

def EditPage(request, page_subject):
    """
    pybo 목록 출력
    """
    data = PageData.objects.get(pk=page_subject)

    if request.method == "POST":
        form = EditForm(request.POST, instance=data)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('kiwi:DetailPage', page_subject=data.subject)
    else:
        form = EditForm(instance=data)
    context = {'form': form, 'pageData': data}
    return render(request, 'NamuKiwi/EditPage.html', context)

def DeletePage(request, page_subject):
    """
    pybo 질문삭제
    """
    data = get_object_or_404(PageData, pk=page_subject)
    data.delete()
    return redirect('kiwi:MainPage')

def CreatePage(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('kiwi:MainPage')
    else:
        form = CreateForm()
    context = {'form': form}
    return render(request, 'NamuKiwi/CreatePage.html', context)

templates/NamuKiwi/CreatePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Namukiwi</title>
    
    <style>
         body{
            margin : 0;
            background-color: #efefef;
        }
        .content-wrapper{
            position: relative;
            background-color: white;
            border: 1px solid #ccc;
            width: 1300px;
            box-sizing: border-box;
            padding: 25px;
            padding-bottom: 60px;
            margin: 0 auto;
        }
        
        .buttons{
            display: inline-block;
            position: absolute;
            height: 33px;
            right: 25px;
        }
        
        .buttons > button{
            height: 33px;
            width: 60px;
            background-color: white;
            border: 1px solid #ccc;
            
            padding: 0;
        }
        
        .buttons > button:not(:last-child){
            border-right: none;
        }
        
        .buttons > button > a{
            display: inline-block;
            width: 58px;
            height: 31px;
            line-height: 33px;
            text-decoration: none;
            padding: 0;
            color : black;
            background-color: white;
        }
        
        .buttons > button > a:hover{
            background-color: #efefef;
        }
        
        .submit{
            float: right;
            width: 100px;
            line-height: 33px;
            background-color: #0275d8;
            border: 1px solid white;
            color: white;
            margin-top: 10px;
        }
        
        .submit:hover{
            cursor: pointer;
            background-color: #23395d;
        }
        
        .disabled{
            background-color: #B8DFF8!important;
        }
        
        .disabled:hover{
            cursor: default;
        }
        
        .form-content{
            width: 1225px;
            height: 750px;
            outline: none;
            border: 1px solid #D6D6D6; 
            border-radius: 4px;

            padding: 10px;
        }
        
        .page-subject{
            display: inline-block;
            font-weight: bold;
            font-size: 3em;
        }
        
        .subject-wrapper{
            line-height: 100px;
            font-size: 2em;
        }
        
        .form-subject{
            font-size: 1.2em;
            outline: none;
            border: 1px solid #D6D6D6; 
            border-radius: 4px;
            padding: 10px;
        }
        
        .serach{
            display: inline-block;
        }
        
        header{
            display: flex;
            justify-content: space-around;
            background-color: #192842;
            height: 50px;
        }
        
        header > h1{
            display: inline-block;
            color: white;
            line-height: 50px;
        }
        
        h1 {
            display: inline-block;
            margin-top: 0;
        }
        
        header > form > .search{
            background-color: white;
            border: none;
            border-right: 1px solid #efefef;
            border-left: 1px solid #efefef;
            box-sizing: border-box;
            outline: none;
            width: 300px;
            height: 50px;
        }
        
        .search-img-wrapper{
            display: inline-block;
            position: relative;
            top: -4px;
            background-color: white;
            height: 50px;
            width: 50px;
            text-align: center;
            
            cursor: pointer;
        }
        
        .search-img-wrapper > .search-img{
            display: inline-block;
            position: relative;
            top: 10px;
            font-weight: bold;
            font-size: 1.5em;
            text-align: center;
            transform: rotate(45deg);
            
            pointer-events: none;
            user-select: none;
        }
    </style>
    
    <script>
        function checkInputData() {
            var button = document.getElementsByClassName('submit')[0];
            var inputs = new Array();
            inputs.push(document.getElementsByClassName('form-subject')[0]);
            inputs.push(document.getElementsByClassName('form-content')[0]);

            console.log(inputs);

            var isEmpty = false;

            for (var i = 0; i < inputs.length; i++){
                if (inputs[i].value == '') {
                    isEmpty = true;
                    break;
                }
                else {
                    isEmpty = false;
                }
            }

            if (isEmpty){
                button.disabled = true;
                button.setAttribute('class', 'submit disabled');
            }
            else{
                button.disabled = false;
                button.setAttribute('class', 'submit')
            }
        }
        
        window.addEventListener('keyup', event=>{
           checkInputData(); 
        });
    </script>
</head>
<body>
    <header>
        <h1>Namukiwi</h1>
        <form id="serach-form" method="post" action="{% url 'kiwi:MainPage' %}">
            {% csrf_token %}
            <input class="search" name="search"><div class="search-img-wrapper" onclick="document.getElementById('serach-form').submit();"><div class="search-img">&#9906;</div></div>
        </form>
    </header>
    <div class="content-wrapper">
        <div class="buttons">
            <button><a href="{% url 'kiwi:MainPage' %}" class="main">메인</a></button>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="page-subject">새 문서 작성</div>
            <div class="subject-wrapper">{{ form.subject }}</div>
            
            {{ form.content }}
            <button type="submit" class="submit disabled" disabled>제출</button>
        </form>
    </div>
</body>
</html>

templates/NamuKiwi/EditPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Namukiwi</title>
    <style>
        body{
            margin : 0;
            background-color: #efefef;
        }
        
        h1{
            display: inline-block;
            margin-top: 0;
        }
        
        h1 > div {
            display: inline-block;
            font-size: 0.7em;
            font-weight: 200;
        }
        
        .editor{
            width: 1225px;
            height: 750px;
            outline: none;
            border: 1px solid #D6D6D6; 
            border-radius: 4px;

            padding: 10px;
        }
        
        .content-wrapper{
            position: relative;
            background-color: white;
            border: 1px solid #ccc;
            width: 1300px;
            box-sizing: border-box;
            padding: 25px;
            padding-bottom: 60px;
            margin: 0 auto;
        }
        
        .buttons{
            display: inline-block;
            position: absolute;
            height: 33px;
            right: 25px;
            
            background-color: #efefef;
        }
        
        .buttons > button{
            height: 33px;
            width: 60px;
            border: 1px solid #ccc;
            
            background-color: white;
            
            padding: 0;
        }
        
        .buttons > button:not(:last-child){
            border-right: none;
        }
        
        .buttons > button > a{
            display: inline-block;
            width: 60px;
            position:relative;
            height: 31px;
            line-height: 33px;
            text-decoration: none;
            padding: 0;
            color : black;
            background-color: white;
        }
        
        .buttons > button > a:hover{
            background-color: #efefef;
        }
        
        .buttons > button > .delete:hover{
            background-color: #F08080;
        }
        
        .buttons > button > .delete{
            color: white;
            background-color: #D9534F;
        }
        
        .buttons > button > .main{
            width: 58px;
        }
        
        .submit{
            float: right;
            width: 100px;
            line-height: 33px;
            background-color: #0275d8;
            border: 1px solid white;
            color: white;
            margin-top: 10px;
        }
        
        .submit:hover{
            cursor: pointer;
            background-color: #23395d;
        }
        
        .disabled{
            background-color: #B8DFF8;
        }
        
        .disabled:hover{
            cursor: default;
        }
        
        .serach{
            display: inline-block;
        }
        
        header{
            display: flex;
            justify-content: space-around;
            background-color: #192842;
            height: 50px;
        }
        
        header > h1{
            color: white;
            line-height: 50px;
        }
        
        header > form > .search{
            background-color: white;
            border: none;
            border-right: 1px solid #efefef;
            border-left: 1px solid #efefef;
            box-sizing: border-box;
            outline: none;
            width: 300px;
            height: 50px;
        }
        
        .search-img-wrapper{
            display: inline-block;
            position: relative;
            top: -4px;
            background-color: white;
            height: 50px;
            width: 50px;
            text-align: center;
            
            cursor: pointer;
        }
        
        .search-img-wrapper > .search-img{
            display: inline-block;
            position: relative;
            top: 10px;
            font-weight: bold;
            font-size: 1.5em;
            text-align: center;
            transform: rotate(45deg);
            
            pointer-events: none;
            user-select: none;
        }
    </style>
    <script>
        function changeContent() {
            var editor = document.getElementsByClassName('editor')[0];
            var content = `{{ pageData.content }}`;
            
            editor.innerHTML = content;
        }
        
        function confirmDelete(){
            var anchor = document.getElementsByClassName('delete')[0];
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = anchor.getAttribute('dataURL');
            }
        }
        
        function checkInputData() {
            var button = document.getElementsByClassName('submit')[0];
            var inputs = new Array();
            inputs.push(document.getElementsByClassName('editor')[0]);

            console.log(inputs);

            var isEmpty = false;

            for (var i = 0; i < inputs.length; i++){
                if (inputs[i].value == '') {
                    isEmpty = true;
                    break;
                }
                else {
                    isEmpty = false;
                }
            }

            if (isEmpty){
                button.disabled = true;
                button.setAttribute('class', 'submit disabled');
            }
            else{
                button.disabled = false;
                button.setAttribute('class', 'submit')
            }
        }
        
        window.addEventListener('keyup', event=>{
           checkInputData(); 
        });
    </script>
</head>
<body onload="changeContent()">
    <header>
        <h1>Namukiwi</h1>
        <form id="serach-form" method="post" action="{% url 'kiwi:MainPage' %}">
            {% csrf_token %}
            <input class="search" name="search"><div class="search-img-wrapper" onclick="document.getElementById('serach-form').submit();"><div class="search-img">&#9906;</div></div>
        </form>
    </header>
    <div class="content-wrapper">
        <div class="buttons">
            <button><a href="{% url 'kiwi:CreatePage' %}" class="create">새 문서</a></button><button><a href="#" class="delete" dataURL="{% url 'kiwi:DeletePage' pageData.subject %}" onclick="confirmDelete()">삭제</a></button><button><a href="{% url 'kiwi:MainPage' %}" class="main">메인</a></button>
        </div>
        <h1>문서 : {{pageData.subject}} <div>(편집)</div></h1>
        <form method="post">
            {% csrf_token %}
            {{ form.content }}
            <button type="submit" class="submit">제출</button>
        </form>
    </div>
</body>
</html>

templates/NamuKiwi/MainPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Namukiwi</title>
    
    <style>
        body{
            margin : 0;
            background-color: #efefef;
        }
        
        h1{
            display: inline-block;
            margin-top: 0;
        }
        
        .list-wrapper{
            display: flex;
            flex-direction: column;
        }
        
        .content-wrapper{
            position: relative;
            background-color: white;
            border: 1px solid #ccc;
            width: 1300px;
            box-sizing: border-box;
            padding: 25px;
            padding-bottom: 60px;
            margin: 0 auto;
        }
        
        .list-wrapper > div > a{
            text-decoration: none;
            color: #0275d8;
        }
        
        .list-wrapper > div > a:hover{
            text-decoration: underline;
        }
        
        .buttons{
            display: inline-block;
            position: absolute;
            height: 33px;
            right: 25px;
        }
        
        .buttons > button{
            height: 33px;
            width: 60px;
            background-color: white;
            border: 1px solid #ccc;
            padding: 0;
        }
        
        .buttons > button:not(:last-child){
            border-right: none;
        }
        
        .buttons{
            background-color: #efefef;
        }
        
        .buttons > button > a{
            display: inline-block;
            width: 58px;
            height: 31px;
            line-height: 33px;
            text-decoration: none;
            padding: 0;
            color : black;
            background-color: white;
        }
        
        .buttons > button > a:hover{
            background-color: #efefef;
        }
        
        .serach{
            display: inline-block;
        }
        
        header{
            display: flex;
            justify-content: space-around;
            background-color: #192842;
            height: 50px;
        }
        
        header > h1{
            color: white;
            line-height: 50px;
        }
        
        header > form > .search{
            background-color: white;
            border: none;
            border-right: 1px solid #efefef;
            border-left: 1px solid #efefef;
            box-sizing: border-box;
            outline: none;
            width: 300px;
            height: 50px;
        }
        
        .search-img-wrapper{
            display: inline-block;
            position: relative;
            top: -4px;
            background-color: white;
            height: 50px;
            width: 50px;
            text-align: center;
            
            cursor: pointer;
        }
        
        .search-img-wrapper > .search-img{
            display: inline-block;
            position: relative;
            top: 10px;
            font-weight: bold;
            font-size: 1.5em;
            text-align: center;
            transform: rotate(45deg);
            
            pointer-events: none;
            user-select: none;
        }
    </style>
    <script>
        window.onload = function(){
            var search = document.getElementsByClassName('search')[0];
            
            search.value = `{{ searchData }}`;
            filter_search();
        }
        
        window.addEventListener('keyup', event=>{
            filter_search();                        
        });
        
        function filter_search(){
            var search = document.getElementsByClassName('search')[0];
            var list = document.getElementsByClassName('list-anchor');
            
            if (search.value != ''){
                for (var i = 0; i < list.length; i++){
                    if (getConstantVowel(list[i].text).toLowerCase().replaceAll(' ', '').includes(getConstantVowel(search.value).toLowerCase().replaceAll(' ', ''))){
                        list[i].style.display = 'inline-block';
                    }
                    else{
                        list[i].style.display = 'none';
                    }
                }    
                console.log(getConstantVowel(search.value));
            }
            else{
                for (var i = 0; i < list.length; i++){
                    list[i].style.display = 'inline-block';
                }
            }
        }
        
        function getConstantVowel(kor) {
            const f = ['ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ',
                       'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅉ',
                       'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'];
            const s = ['ㅏ', 'ㅐ', 'ㅑ', 'ㅒ', 'ㅓ', 'ㅔ', 'ㅕ',
                       'ㅖ', 'ㅗ', 'ㅘ', 'ㅙ', 'ㅚ', 'ㅛ', 'ㅜ',
                       'ㅝ', 'ㅞ', 'ㅟ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ'];
            const t = ['', 'ㄱ', 'ㄲ', 'ㄳ', 'ㄴ', 'ㄵ', 'ㄶ',
                       'ㄷ', 'ㄹ', 'ㄺ', 'ㄻ', 'ㄼ', 'ㄽ', 'ㄾ',
                       'ㄿ', 'ㅀ', 'ㅁ', 'ㅂ', 'ㅄ', 'ㅅ', 'ㅆ',
                       'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'];
            
            const ga = 44032;
            var uni = new Array(kor.length);
            for (var i = 0; i < kor.length; i++){
                
                uni[i] = kor[i].charCodeAt(0);

                uni[i] = uni[i] - ga;
            }
            
            var check = /[가-힣]/;
            var newString = '';
            
            for (var i = 0; i < kor.length; i++){
                if (/[ㄱ-ㅎ]/.test(kor[i]) && !check.test(kor[i])){
                    newString += String.fromCharCode(uni[i] + ga);
                    continue;
                }    
                
                if (check.test(kor[i])){
                    newString += (f[parseInt(uni[i] / 588)] + s[parseInt((uni[i] - (parseInt(uni[i] / 588) * 588)) / 28)] + t[parseInt(uni[i] % 28)]);
                }
                else{
                    newString += String.fromCharCode(uni[i] + ga);
                }
            }

            return newString;
        }
    </script>
</head>
<body>
    <header>
        <h1>Namukiwi</h1>
        <form id="serach-form" method="post" action="{% url 'kiwi:MainPage' %}">
            {% csrf_token %}
            <input class="search" name="search"><div class="search-img-wrapper" onclick="document.getElementById('serach-form').submit();"><div class="search-img">&#9906;</div></div>
        </form>
    </header>
    <div class="content-wrapper">
        <div class="buttons">
            <button><a href="{% url 'kiwi:CreatePage' %}" class="create">새 문서</a></button>
        </div>
        <h1>문서 목록</h1>
        {% if pageDataList %}
            <div class="list-wrapper">
            {% for data in pageDataList %}
                <div><a href="{% url 'kiwi:DetailPage' data.subject %}" class="list-anchor">{{data.subject}}</a></div>
            {% endfor %}
            </div>
        {% else %}
            <div>x</div>
        {% endif %}
    </div>
</body>
</html>